language: node_js
node_js:
- "7.4.0"
sudo: false
cache:
  directories:
  - node_modules
  - vendor/bundle
  - /home/travis/.rvm/
before_install:
- rvm install 2.6.3
- rvm use 2.6.3
- gem install bundler
- bundle install --path vendor/bundle
deploy:
  skip_cleanup: true
  provider: script
  script: rvm 2.6.3 do ./scripts/deploy.sh
  on:
    branch: source
