language: node_js
node_js:
- 7.4.0
sudo: false
cache:
  directories:
  - node_modules
  - vendor/bundle
  - "/home/travis/.rvm"
  - "/home/travis/.nvm"
before_install:
- nvm install 12.4.0
- nvm use 12.4.0
- rvm install 2.6.3
- rvm use 2.6.3
- gem install bundler
install:
- npm install
- bundle install --path vendor/bundle
script:
- rvm 2.6.3 do bundle exec middleman build
deploy:
  - skip_cleanup: true
    provider: script
    script: rvm 2.6.3 do ./scripts/deploy.sh
    on:
      branch: source
  - provider: releases
    api_key:
      secure: VHkK3X8fi21fJykAuxbxb2IEW+SNZkynIoc4j0igEWzLMRYYSKEXLp/3P/Lc/m/JZdXiG2tkPYqCaXcv78Qu1q5/M8JXg9evGc3PXssVy+jQNjZmnXGKjORbAD19Jdw5s1RLuFwjf3iX8I07oIsXLjZkbBkKGkhNBnXTq1LKnIN0sP/mTCaSNQVJ+NU8s035OEbxK0ANSu5aqYkgEn7ABcRg9gGmOj+vdP065WF6Fy2raK7ppLvD+UvZS8CC7LreuEG9hrVjY6iUBq5z8vMAPQY0Pcaj+eAbg4ZRi3ZA5otoq8EyRA1PVSe4lyEVm+Hco9hv/l7qDONouBWMbrjF83svlucEkkWzgk+Zl4apEPwfFimNZ+k7/r0k+RZqW7UclV4eq+ZXpSgsEwz1PDVfE8BcN82ky92Xm0ibOkg4gdUyWbWu4ik/opvAkslkSBEpBFW5/njLknUaNXx2bet3NA0WQkiQkehOk2mLju5+W3o+wzltQRG+viRT42l6TKY7MAgJN/IQ7EfKD8Z2q4lKnoD+lr0q6xqBZU1r+MRMCiWFsR8DCMynGv6woZW2myNHcSOdrp7qwE/F9YMzHEr0MJGREtAlw7m0l7zLKeAbOPzk7WHT3TglbgZavK2FDCWQO5k91DdcnCD8LwNI9EVSaxamH6SvLZI3MjaiejnvjqY=
    file: build
    on:
      branch: source
    skip_cleanup: true
